# Neon PostgreSQL Datasource
apiVersion: 1

datasources:
  - name: Neon Marketing DB
    type: postgres
    access: proxy
    url: ep-ancient-waterfall-a42vy0du-pooler.us-east-1.aws.neon.tech:5432
    database: Marketing DB
    user: Marketing DB_owner
    secureJsonData:
      password: npg_OsE4Z2oPCpiT
    jsonData:
      sslmode: require
      postgresVersion: 1700
    isDefault: true
    editable: true
